export const stylePresets = [
  ['notion_kanban', 'Notion Kanban'], ['dashboard_saas', 'Dashboard SaaS'], ['ted_talk', 'TED Talk'], ['corporate_clean', 'Corporate Clean'], ['swiss_grid_style', 'Swiss Grid'], ['data_report', 'Data Report'],
  ['lego_style', 'Lego Style'], ['gamified', 'Gamified'], ['comic_book', 'Comic Book'], ['urban_graffiti', 'Urban Graffiti'], ['pop_art', 'Pop Art'], ['retro_arcade', 'Retro Arcade'],
  ['da_vinci_sketch', 'Da Vinci Sketch'], ['risograph', 'Risograph'], ['paper_cutout', 'Paper Cutout'], ['wes_anderson', 'Wes Anderson'], ['akvarel', 'Akvarel'], ['bauhaus', 'Bauhaus'],
  ['wireframe', 'Wireframe'], ['neon_dark', 'Neon Dark'], ['futurist_hud', 'Futurist HUD'], ['london_metro', 'London Metro'], ['blueprint', 'Blueprint'], ['minimal_ui', 'Minimal UI'],
  ['vintage_poster', 'Vintage Poster'], ['claymation', 'Claymation'], ['collage_papier', 'Collage Papier'], ['mind_map_marker', 'Mind Map Marker'], ['natural_sketch', 'Natural Sketch'], ['avant_garde', 'Avant-Garde'],
  ['nordic', 'Nordic Clean (severský minimalismus)'], ['art_deco', 'Art Déco (elegance + zlato)'], ['cubism_cz', 'Czech Cubism (krystalická geometrie)'], ['british_editorial', 'British Editorial (novinová autorita)'], ['american_bold', 'American Bold (magazínová energie)'], ['botanical', 'Botanical Atlas (19. století)'], ['surreal_space', 'Surreal Space Collage (retro-vesmír)'], ['mediterranean_mosaic', 'Mediterranean Mosaic (měď + olivy)'],
] as const;

export const layoutPresets = [
  ['standard_grid', 'Standard Grid (3–5 bloků)'], ['swiss_grid', 'Swiss Grid (přesná mřížka)'], ['timeline', 'Timeline (vertikální časová osa)'], ['radial', 'Radial (střed + segmenty)'], ['magazine', 'Magazine (headline + 2 sloupce)'], ['dashboard', 'Dashboard (KPI pás + 2×2 grid)'], ['research_poster', 'Research Poster (3 sloupce)'], ['brutalist_poster', 'Brutalist Poster (plakát + diagonály)'], ['czech_cubism', 'Česko (Bohemian Cubism + Secese)'], ['germany_bauhaus', 'Německo (Bauhaus Functional Grid)'], ['france_art_deco_parisien', 'Francie (Art Déco Parisien)'], ['uk_british_editorial', 'Velká Británie (British Editorial)'], ['usa_american_bold', 'USA (American Bold Magazine)'], ['italy_renaissance', 'Itálie (Renaissance Symmetry)'], ['spain_iberian_mosaic', 'Španělsko (Iberian Mosaic)'], ['austria_wiener_secession', 'Rakousko (Wiener Secession)'], ['greece_classical_frieze', 'Řecko (Classical Frieze)'], ['cyprus_mediterranean_mosaic', 'Kypr (Mediterranean Mosaic)'], ['norway_fjord_nordic', 'Norsko (Fjord Nordic)'], ['sweden_scandinavian_clean', 'Švédsko (Scandinavian Clean)'], ['canada_northern_clean', 'Kanada (Northern Clean)'], ['brazil_tropical_modern', 'Brazílie (Tropical Modern)'], ['japan_zen_minimal', 'Japonsko (Zen Minimal)'], ['china_ink_scroll', 'Čína (Ink Scroll)'], ['india_mandala_infographic', 'Indie (Mandala Grid)'], ['egypt_papyrus_archaeology', 'Egypt (Papyrus Archaeology)'], ['australia_oceanic_modern', 'Austrálie (Oceanic Modern)'],
] as const;

export const colorModes = [
  ['auto', 'Automaticky (dle stylu)'], ['corporate_blue_white', 'Modrá & bílá (corporate)'], ['warm_terracotta', 'Teplá (oranžová, červená, okr)'], ['pastel_soft', 'Pastelová (jemná, uklidňující)'], ['neon_future', 'Neon (futuristická)'], ['nature_earth', 'Přírodní (zelená, hnědá, béžová)'], ['monochrome', 'Monochromatická'], ['luxury_black_gold', 'Luxusní (černá + zlato)'], ['academic_navy_gray', 'Akademická (tmavě modrá + šedá)'], ['educational_blue_yellow', 'Edukační (modrá + žlutá kontrast)'], ['high_tech_indigo_cyan', 'High-tech (indigo + cyan)'], ['vintage_sepia', 'Vintage (sepia + krémová)'], ['crisis_red_yellow_black', 'Krizová (červená + žlutá + černá)'], ['sport_red_navy', 'Sportovní (červená + navy)'], ['health_clean', 'Zdravotnická (čistá bílá + modrozelená)'], ['eco_green_beige', 'Zelená ekonomika (tmavě zelená + béžová)'], ['night_mode', 'Noční režim (tmavý + vysoký kontrast)'],
] as const;
